#!/bin/bash
#
# Riyad Preukschas <riyad@informatik.uni-bremen.de>
#
# Restores previously backed-up files to your Android phone.
# You still need to restore your apps and config by running TitaniumBackup.


# for easy listing of directory contents starting with '.'
GLOBIGNORE=.:..
# on a running Android /sdcard is symlinked to /storage/emulated/[legacy|0]
# but in TWRP it's directly mounted to /sdcard (so the other dirs aren't there)
readonly ANDROID_STORAGE="/sdcard"
readonly RSYNC_CONFIG="/data/local/tmp/rsync.conf"
readonly RSYNC_DEVICE_PORT=1873  # should be above 1024 to be able to bind to without root
readonly RSYNC_LOCAL_PORT=6010
RSYNC_BIN="rsync"
# these are relative to BACKUP_DIR
readonly TB_DIR="TitaniumBackup"
readonly TB_APKS="TitaniumBackup.apk TitaniumBackupPro.apk"
readonly PRIO_DIRS="WhatsApp DCIM Pictures"
readonly SKIP_DIRS="${TB_DIR} ${TB_APKS} ${PRIO_DIRS}"

alias adb="adb -d"
# thanks to http://stackoverflow.com/questions/8063228/how-do-i-check-if-a-variable-exists-in-a-list-in-bash
contains() {
  local list="$1"
  local item="$2"
  [[ ${list} =~ (^|[[:space:]])${item}($|[[:space:]]) ]]
}
adb_install() {
  adb install "$1"
}
adb_push() {
  adb push -p "$1" "${ANDROID_STORAGE}/$1"
}
rsync_cleanup() {
  adb forward --remove tcp:${RSYNC_LOCAL_PORT}
  adb shell rm -f "${RSYNC_CONFIG}"
}
rsync_push() {
  rsync --partial --progress --archive --human-readable -n --delete --filter='- .DS_Store' "$1/" "rsync://localhost:6010/root/$2/"
  : rc $?
}
rsync_setup() {
  # from http://blog.josefsson.org/2015/11/28/automatic-android-replicant-backup-over-usb-using-rsync/
  # and http://ptspts.blogspot.de/2015/03/how-to-use-rsync-over-adb-on-android.html
  adb shell "echo \"address = 127.0.0.1\nport = ${RSYNC_DEVICE_PORT}\n\n[root]\npath = /\nuse chroot = false\nread only = false\"" \> "${RSYNC_CONFIG}"
  adb shell ${RSYNC_BIN} --daemon --no-detach --config="${RSYNC_CONFIG}" &  # for debugging --log-file=/proc/self/fd/2
  adb forward tcp:${RSYNC_LOCAL_PORT} tcp:${RSYNC_DEVICE_PORT}
  sleep 2
}


# make sure we get a path to restore stuff from
if [[ -z "$1" ]]; then
  echo "Please specify the directory your backups are in!"
  exit 1
else
  readonly BACKUP_DIR="$1"
fi


if [[ ! -d "${BACKUP_DIR}" ]]; then
  echo "'${BACKUP_DIR}' is not a directory."
  exit 1
fi


rsync_setup


echo "Restoring TitaniumBackup data first ..."
if [ ! -d "${BACKUP_DIR}/${TB_DIR}" ]; then
  echo "Can't find TitaniumBackup data directory"
  exit 1
fi
rsync_push "${BACKUP_DIR}/${TB_DIR}" "${ANDROID_STORAGE}/${TB_DIR}"


# install TitaniumBackup so we can start restoring stuff on the device itself
echo "Restoring TitaniumBackup apps ..."
for apk in ${TB_APKS}; do
  if [[ -f "${BACKUP_DIR}/${apk}" ]]; then
    adb_install "${BACKUP_DIR}/${apk}"
  else
    echo "Can't find TitaniumBackup app ${apk}."
    exit 1
  fi
done


echo "Restoring some other things with priority ..."
for dir in ${PRIO_DIRS}; do
  [[ ! -d "${BACKUP_DIR}/${dir}" ]] && continue
  rsync_push "${BACKUP_DIR}/${dir}" "${ANDROID_STORAGE}/${dir}"
done


echo "Restoring all the rest ..."
for dir in *; do
  if $(contains "${SKIP_DIRS}" "${dir}"); then
    echo "Skipping previously restored '${dir}'"
    continue
  fi
  rsync_push "${BACKUP_DIR}/${dir}" "${ANDROID_STORAGE}/${dir}"
done
rsync_cleanup
echo "... Done!"
